version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./backend
    ports:
      - "3002:3000"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - NODE_ENV=development
    depends_on:
      - database

  database:
    image: postgres:14
    environment:
      POSTGRES_USER: omnitensor
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: marketplace
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local
