name: Marketplace Deployment
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    name: Deploy Marketplace
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies for frontend
        run: npm install --legacy-peer-deps
        working-directory: frontend

      - name: Build frontend
        run: npm run build
        working-directory: frontend

      - name: Install dependencies for backend
        run: npm install
        working-directory: backend

      - name: Start backend server
        run: npm start
        working-directory: backend

      - name: Upload Deployment Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: deployment-artifacts
          path: |
            frontend/build
            backend
